package com.prasanna.Exception;
import java.util.Scanner;

public class Main2 {

	public static void main(String[] args)  throws ArithmeticException {
		// TODO Auto-generated method stub
		System.out.println("connection is established");
		Scanner scan=new Scanner(System.in);
		int a=10;
		int b=0;
		int c=a/b;
		System.out.println(c);
		System.out.println("connection terminated");

	}

}
